[project]
name = "fastapi-geo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "redis>=5.2.1",
    "uvicorn>=0.34.0",
]
